! Code generated by kwxgen. DO NOT EDIT.
module wx_controls
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    use wx_string, only: to_wxstring, from_wxstring
    implicit none
    private

    ! wxButton
    public :: wx_button_create, wx_button_set_default

    ! wxTextCtrl
    public :: wx_text_ctrl_create
    public :: wx_text_ctrl_get_value, wx_text_ctrl_set_value
    public :: wx_text_ctrl_change_value
    public :: wx_text_ctrl_clear
    public :: wx_text_ctrl_write_text, wx_text_ctrl_append_text
    public :: wx_text_ctrl_is_modified, wx_text_ctrl_is_editable
    public :: wx_text_ctrl_get_number_of_lines
    public :: wx_text_ctrl_set_hint

    ! wxStaticText
    public :: wx_static_text_create

    ! wxPanel
    public :: wx_panel_create

    ! wxCheckBox
    public :: wx_checkbox_create
    public :: wx_checkbox_get_value, wx_checkbox_set_value

    ! wxRadioButton
    public :: wx_radiobutton_create
    public :: wx_radiobutton_get_value, wx_radiobutton_set_value

    ! wxChoice
    public :: wx_choice_create, wx_choice_append
    public :: wx_choice_delete, wx_choice_clear, wx_choice_get_count
    public :: wx_choice_get_selection, wx_choice_set_selection
    public :: wx_choice_find_string
    public :: wx_choice_get_string, wx_choice_set_string

    ! wxListBox
    public :: wx_listbox_create, wx_listbox_append
    public :: wx_listbox_delete, wx_listbox_clear, wx_listbox_get_count
    public :: wx_listbox_get_selection, wx_listbox_set_selection
    public :: wx_listbox_find_string
    public :: wx_listbox_get_string, wx_listbox_set_string
    public :: wx_listbox_is_selected

    ! wxComboBox
    public :: wx_combobox_create, wx_combobox_append
    public :: wx_combobox_delete, wx_combobox_clear, wx_combobox_get_count
    public :: wx_combobox_get_selection, wx_combobox_set_selection
    public :: wx_combobox_find_string
    public :: wx_combobox_get_string, wx_combobox_set_string
    public :: wx_combobox_get_value, wx_combobox_set_value

contains

    !--- wxButton ---

    function wx_button_create(label, parent, id, x, y, width, height, style) &
            result(button)
        character(len=*), intent(in) :: label
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxButton_t) :: button

        type(c_ptr) :: label_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        label_ptr = to_wxstring(label)
        button%ptr = wxButton_Create(parent%ptr, c_id, label_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(label_ptr)
    end function

    subroutine wx_button_set_default(button)
        type(wxButton_t), intent(in) :: button
        call wxButton_SetDefault(button%ptr)
    end subroutine

    !--- wxTextCtrl ---

    function wx_text_ctrl_create(parent, value, id, x, y, width, height, style) &
            result(ctrl)
        class(wxWindow_t), intent(in) :: parent
        character(len=*), intent(in), optional :: value
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxTextCtrl_t) :: ctrl

        type(c_ptr) :: val_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        if (present(value)) then
            val_ptr = to_wxstring(value)
        else
            val_ptr = to_wxstring("")
        end if

        ctrl%ptr = wxTextCtrl_Create(parent%ptr, c_id, val_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(val_ptr)
    end function

    function wx_text_ctrl_get_value(ctrl) result(value)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=:), allocatable :: value
        type(c_ptr) :: ws_ptr
        ws_ptr = wxTextCtrl_GetValue(ctrl%ptr)
        value = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_text_ctrl_set_value(ctrl, value)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=*), intent(in) :: value
        type(c_ptr) :: val_ptr
        val_ptr = to_wxstring(value)
        call wxTextCtrl_SetValue(ctrl%ptr, val_ptr)
        call wxString_Delete(val_ptr)
    end subroutine

    subroutine wx_text_ctrl_change_value(ctrl, value)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=*), intent(in) :: value
        type(c_ptr) :: val_ptr
        val_ptr = to_wxstring(value)
        call wxTextCtrl_ChangeValue(ctrl%ptr, val_ptr)
        call wxString_Delete(val_ptr)
    end subroutine

    subroutine wx_text_ctrl_clear(ctrl)
        type(wxTextCtrl_t), intent(in) :: ctrl
        call wxTextCtrl_Clear(ctrl%ptr)
    end subroutine

    subroutine wx_text_ctrl_write_text(ctrl, text)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=*), intent(in) :: text
        type(c_ptr) :: text_ptr
        text_ptr = to_wxstring(text)
        call wxTextCtrl_WriteText(ctrl%ptr, text_ptr)
        call wxString_Delete(text_ptr)
    end subroutine

    subroutine wx_text_ctrl_append_text(ctrl, text)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=*), intent(in) :: text
        type(c_ptr) :: text_ptr
        text_ptr = to_wxstring(text)
        call wxTextCtrl_AppendText(ctrl%ptr, text_ptr)
        call wxString_Delete(text_ptr)
    end subroutine

    function wx_text_ctrl_is_modified(ctrl) result(modified)
        type(wxTextCtrl_t), intent(in) :: ctrl
        logical :: modified
        modified = (wxTextCtrl_IsModified(ctrl%ptr) /= 0)
    end function

    function wx_text_ctrl_is_editable(ctrl) result(editable)
        type(wxTextCtrl_t), intent(in) :: ctrl
        logical :: editable
        editable = (wxTextCtrl_IsEditable(ctrl%ptr) /= 0)
    end function

    function wx_text_ctrl_get_number_of_lines(ctrl) result(nlines)
        type(wxTextCtrl_t), intent(in) :: ctrl
        integer :: nlines
        nlines = int(wxTextCtrl_GetNumberOfLines(ctrl%ptr))
    end function

    subroutine wx_text_ctrl_set_hint(ctrl, hint)
        type(wxTextCtrl_t), intent(in) :: ctrl
        character(len=*), intent(in) :: hint
        type(c_ptr) :: hint_ptr
        integer(c_int) :: res
        hint_ptr = to_wxstring(hint)
        res = wxTextEntry_SetHint(ctrl%ptr, hint_ptr)
        call wxString_Delete(hint_ptr)
    end subroutine


        
    !--- wxStaticText ---

    function wx_static_text_create(label, parent, id, x, y, width, height, &
            style) result(st)
        character(len=*), intent(in) :: label
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxStaticText_t) :: st

        type(c_ptr) :: label_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        label_ptr = to_wxstring(label)
        st%ptr = wxStaticText_Create(parent%ptr, c_id, label_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(label_ptr)
    end function

    !--- wxPanel ---

    function wx_panel_create(parent, id, x, y, width, height, style) &
            result(panel)
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxPanel_t) :: panel

        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = wxTAB_TRAVERSAL()
        if (present(style)) c_style = style

        panel%ptr = wxPanel_Create(parent%ptr, c_id, &
            c_x, c_y, c_w, c_h, c_style)
    end function

    !--- wxCheckBox ---

    function wx_checkbox_create(label, parent, id, x, y, width, height, &
            style) result(cb)
        character(len=*), intent(in) :: label
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxCheckBox_t) :: cb

        type(c_ptr) :: label_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        label_ptr = to_wxstring(label)
        cb%ptr = wxCheckBox_Create(parent%ptr, c_id, label_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(label_ptr)
    end function

    function wx_checkbox_get_value(cb) result(checked)
        type(wxCheckBox_t), intent(in) :: cb
        logical :: checked
        checked = (wxCheckBox_GetValue(cb%ptr) /= 0)
    end function

    subroutine wx_checkbox_set_value(cb, checked)
        type(wxCheckBox_t), intent(in) :: cb
        logical, intent(in) :: checked
        integer(c_int) :: val
        val = 0_c_int
        if (checked) val = 1_c_int
        call wxCheckBox_SetValue(cb%ptr, val)
    end subroutine

    !--- wxRadioButton ---

    function wx_radiobutton_create(label, parent, id, x, y, width, height, &
            style) result(rb)
        character(len=*), intent(in) :: label
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxRadioButton_t) :: rb

        type(c_ptr) :: label_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        label_ptr = to_wxstring(label)
        rb%ptr = wxRadioButton_Create(parent%ptr, c_id, label_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(label_ptr)
    end function

    function wx_radiobutton_get_value(rb) result(selected)
        type(wxRadioButton_t), intent(in) :: rb
        logical :: selected
        selected = (wxRadioButton_GetValue(rb%ptr) /= 0)
    end function

    subroutine wx_radiobutton_set_value(rb, selected)
        type(wxRadioButton_t), intent(in) :: rb
        logical, intent(in) :: selected
        integer(c_int) :: val
        val = 0_c_int
        if (selected) val = 1_c_int
        call wxRadioButton_SetValue(rb%ptr, val)
    end subroutine

    !--- wxChoice ---

    function wx_choice_create(parent, id, x, y, width, height, style) &
            result(choice)
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxChoice_t) :: choice

        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        choice%ptr = wxChoice_Create(parent%ptr, c_id, &
            c_x, c_y, c_w, c_h, 0_c_int, c_null_ptr, c_style)
    end function

    subroutine wx_choice_append(choice, item)
        type(wxChoice_t), intent(in) :: choice
        character(len=*), intent(in) :: item
        type(c_ptr) :: item_ptr
        item_ptr = to_wxstring(item)
        call wxChoice_Append(choice%ptr, item_ptr)
        call wxString_Delete(item_ptr)
    end subroutine

    subroutine wx_choice_delete(choice, index)
        type(wxChoice_t), intent(in) :: choice
        integer, intent(in) :: index
        call wxChoice_Delete(choice%ptr, int(index, c_int))
    end subroutine

    subroutine wx_choice_clear(choice)
        type(wxChoice_t), intent(in) :: choice
        call wxChoice_Clear(choice%ptr)
    end subroutine

    function wx_choice_get_count(choice) result(n)
        type(wxChoice_t), intent(in) :: choice
        integer :: n
        n = int(wxChoice_GetCount(choice%ptr))
    end function

    function wx_choice_get_selection(choice) result(sel)
        type(wxChoice_t), intent(in) :: choice
        integer :: sel
        sel = int(wxChoice_GetSelection(choice%ptr))
    end function

    subroutine wx_choice_set_selection(choice, index)
        type(wxChoice_t), intent(in) :: choice
        integer, intent(in) :: index
        call wxChoice_SetSelection(choice%ptr, int(index, c_int))
    end subroutine

    function wx_choice_find_string(choice, str) result(index)
        type(wxChoice_t), intent(in) :: choice
        character(len=*), intent(in) :: str
        integer :: index
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        index = int(wxChoice_FindString(choice%ptr, str_ptr))
        call wxString_Delete(str_ptr)
    end function

    function wx_choice_get_string(choice, index) result(str)
        type(wxChoice_t), intent(in) :: choice
        integer, intent(in) :: index
        character(len=:), allocatable :: str
        type(c_ptr) :: ws_ptr
        ws_ptr = wxChoice_GetString(choice%ptr, int(index, c_int))
        str = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_choice_set_string(choice, index, str)
        type(wxChoice_t), intent(in) :: choice
        integer, intent(in) :: index
        character(len=*), intent(in) :: str
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        call wxChoice_SetString(choice%ptr, int(index, c_int), str_ptr)
        call wxString_Delete(str_ptr)
    end subroutine
        

    !--- wxListBox ---

    function wx_listbox_create(parent, id, x, y, width, height, style) &
            result(lb)
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxListBox_t) :: lb

        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        lb%ptr = wxListBox_Create(parent%ptr, c_id, &
            c_x, c_y, c_w, c_h, 0_c_int, c_null_ptr, c_style)
    end function

    subroutine wx_listbox_append(lb, item)
        type(wxListBox_t), intent(in) :: lb
        character(len=*), intent(in) :: item
        type(c_ptr) :: item_ptr
        item_ptr = to_wxstring(item)
        call wxListBox_Append(lb%ptr, item_ptr)
        call wxString_Delete(item_ptr)
    end subroutine

    subroutine wx_listbox_delete(lb, index)
        type(wxListBox_t), intent(in) :: lb
        integer, intent(in) :: index
        call wxListBox_Delete(lb%ptr, int(index, c_int))
    end subroutine

    subroutine wx_listbox_clear(lb)
        type(wxListBox_t), intent(in) :: lb
        call wxListBox_Clear(lb%ptr)
    end subroutine

    function wx_listbox_get_count(lb) result(n)
        type(wxListBox_t), intent(in) :: lb
        integer :: n
        n = int(wxListBox_GetCount(lb%ptr))
    end function

    function wx_listbox_get_selection(lb) result(sel)
        type(wxListBox_t), intent(in) :: lb
        integer :: sel
        sel = int(wxListBox_GetSelection(lb%ptr))
    end function

    subroutine wx_listbox_set_selection(lb, index, sel)
        type(wxListBox_t), intent(in) :: lb
        integer, intent(in) :: index
        logical, intent(in), optional :: sel
        integer(c_int) :: c_sel
        c_sel = 1_c_int
        if (present(sel)) then
            c_sel = 0_c_int
            if (sel) c_sel = 1_c_int
        end if
        call wxListBox_SetSelection(lb%ptr, int(index, c_int), c_sel)
    end subroutine

    function wx_listbox_find_string(lb, str) result(index)
        type(wxListBox_t), intent(in) :: lb
        character(len=*), intent(in) :: str
        integer :: index
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        index = int(wxListBox_FindString(lb%ptr, str_ptr))
        call wxString_Delete(str_ptr)
    end function

    function wx_listbox_get_string(lb, index) result(str)
        type(wxListBox_t), intent(in) :: lb
        integer, intent(in) :: index
        character(len=:), allocatable :: str
        type(c_ptr) :: ws_ptr
        ws_ptr = wxListBox_GetString(lb%ptr, int(index, c_int))
        str = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_listbox_set_string(lb, index, str)
        type(wxListBox_t), intent(in) :: lb
        integer, intent(in) :: index
        character(len=*), intent(in) :: str
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        call wxListBox_SetString(lb%ptr, int(index, c_int), str_ptr)
        call wxString_Delete(str_ptr)
    end subroutine

    function wx_listbox_is_selected(lb, index) result(selected)
        type(wxListBox_t), intent(in) :: lb
        integer, intent(in) :: index
        logical :: selected
        selected = (wxListBox_IsSelected(lb%ptr, int(index, c_int)) /= 0)
    end function

    !--- wxComboBox ---

    function wx_combobox_create(parent, id, value, x, y, width, height, &
            style) result(cb)
        class(wxWindow_t), intent(in) :: parent
        integer, intent(in), optional :: id
        character(len=*), intent(in), optional :: value
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxComboBox_t) :: cb

        type(c_ptr) :: val_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style

        if (present(value)) then
            val_ptr = to_wxstring(value)
        else
            val_ptr = to_wxstring("")
        end if

        cb%ptr = wxComboBox_Create(parent%ptr, c_id, val_ptr, &
            c_x, c_y, c_w, c_h, 0_c_int, c_null_ptr, c_style)
        call wxString_Delete(val_ptr)
    end function

    subroutine wx_combobox_append(cb, item)
        type(wxComboBox_t), intent(in) :: cb
        character(len=*), intent(in) :: item
        type(c_ptr) :: item_ptr
        item_ptr = to_wxstring(item)
        call wxComboBox_Append(cb%ptr, item_ptr)
        call wxString_Delete(item_ptr)
    end subroutine

    subroutine wx_combobox_delete(cb, index)
        type(wxComboBox_t), intent(in) :: cb
        integer, intent(in) :: index
        call wxComboBox_Delete(cb%ptr, int(index, c_int))
    end subroutine

    subroutine wx_combobox_clear(cb)
        type(wxComboBox_t), intent(in) :: cb
        call wxComboBox_Clear(cb%ptr)
    end subroutine

    function wx_combobox_get_count(cb) result(n)
        type(wxComboBox_t), intent(in) :: cb
        integer :: n
        n = int(wxComboBox_GetCount(cb%ptr))
    end function

    function wx_combobox_get_selection(cb) result(sel)
        type(wxComboBox_t), intent(in) :: cb
        integer :: sel
        sel = int(wxComboBox_GetSelection(cb%ptr))
    end function

    subroutine wx_combobox_set_selection(cb, index)
        type(wxComboBox_t), intent(in) :: cb
        integer, intent(in) :: index
        call wxComboBox_SetSelection(cb%ptr, int(index, c_int))
    end subroutine

    function wx_combobox_find_string(cb, str) result(index)
        type(wxComboBox_t), intent(in) :: cb
        character(len=*), intent(in) :: str
        integer :: index
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        index = int(wxComboBox_FindString(cb%ptr, str_ptr))
        call wxString_Delete(str_ptr)
    end function

    function wx_combobox_get_string(cb, index) result(str)
        type(wxComboBox_t), intent(in) :: cb
        integer, intent(in) :: index
        character(len=:), allocatable :: str
        type(c_ptr) :: ws_ptr
        ws_ptr = wxComboBox_GetString(cb%ptr, int(index, c_int))
        str = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_combobox_set_string(cb, index, str)
        type(wxComboBox_t), intent(in) :: cb
        integer, intent(in) :: index
        character(len=*), intent(in) :: str
        type(c_ptr) :: str_ptr
        str_ptr = to_wxstring(str)
        call wxComboBox_SetString(cb%ptr, int(index, c_int), str_ptr)
        call wxString_Delete(str_ptr)
    end subroutine

    function wx_combobox_get_value(cb) result(value)
        type(wxComboBox_t), intent(in) :: cb
        character(len=:), allocatable :: value
        type(c_ptr) :: ws_ptr
        ws_ptr = wxComboBox_GetValue(cb%ptr)
        value = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_combobox_set_value(cb, value)
        type(wxComboBox_t), intent(in) :: cb
        character(len=*), intent(in) :: value
        type(c_ptr) :: val_ptr
        val_ptr = to_wxstring(value)
        call wxComboBox_SetValue(cb%ptr, val_ptr)
        call wxString_Delete(val_ptr)
    end subroutine

end module wx_controls
