! Code generated by kwxgen. DO NOT EDIT.
module wx_dialogs
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    use wx_string, only: to_wxstring
    implicit none
    private

    public :: wx_message_box

contains

    function wx_message_box(message, caption, style, parent) result(res)
        character(len=*), intent(in) :: message
        character(len=*), intent(in), optional :: caption
        integer, intent(in), optional :: style
        class(wxWindow_t), intent(in), optional :: parent
        integer :: res

        type(c_ptr) :: msg_ptr, cap_ptr, parent_ptr
        integer(c_int) :: c_style

        msg_ptr = to_wxstring(message)
        if (present(caption)) then
            cap_ptr = to_wxstring(caption)
        else
            cap_ptr = to_wxstring("Message")
        end if
        c_style = ior(wxOK(), wxICON_INFORMATION())
        if (present(style)) c_style = int(style, c_int)
        parent_ptr = c_null_ptr
        if (present(parent)) parent_ptr = parent%ptr

        res = int(kwxMessageBox(msg_ptr, cap_ptr, c_style, &
            parent_ptr, -1_c_int, -1_c_int))

        call wxString_Delete(msg_ptr)
        call wxString_Delete(cap_ptr)
    end function

end module wx_dialogs
