! Code generated by kwxgen. DO NOT EDIT.
module wx_events
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi, wxClosure_C_ptr => wxClosure_Create
    use wx_string, only: from_wxstring
    implicit none
    private

    ! Connection
    public :: wx_connect, wx_disconnect

    ! Base event accessors
    public :: wx_event_get_id, wx_event_get_type, wx_event_skip
    public :: wx_event_get_timestamp, wx_event_get_skipped
    public :: wx_event_is_command_event

    ! Command event accessors
    public :: wx_command_event_get_string
    public :: wx_command_event_get_selection
    public :: wx_command_event_get_int
    public :: wx_command_event_get_extra_long
    public :: wx_command_event_is_checked
    public :: wx_command_event_is_selection

    ! Abstract callback interface
    public :: event_callback

    abstract interface
        subroutine event_callback(fun, data, evt) bind(C)
            import :: c_ptr
            type(c_ptr), value :: fun, data, evt
        end subroutine event_callback
    end interface

    ! Private wxClosure binding with c_funptr
    interface
        function wxClosure_Create(fun, data) bind(C, name="wxClosure_Create")
            import :: c_ptr, c_funptr
            type(c_funptr), value :: fun
            type(c_ptr), value :: data
            type(c_ptr) :: wxClosure_Create
        end function
    end interface

contains

    !--- Connection ---

    subroutine wx_connect(window, event_type, handler, user_data, id, last_id)
        class(wxWindow_t), intent(in) :: window
        integer, intent(in) :: event_type
        procedure(event_callback) :: handler
        type(c_ptr), intent(in), optional :: user_data
        integer, intent(in), optional :: id
        integer, intent(in), optional :: last_id

        type(c_funptr) :: fptr
        type(c_ptr) :: data_ptr
        integer(c_int) :: c_first, c_last, c_type, dummy

        fptr = c_funloc(handler)
        data_ptr = c_null_ptr
        if (present(user_data)) data_ptr = user_data
        c_first = -1_c_int
        if (present(id)) c_first = int(id, c_int)
        c_last = c_first
        if (present(last_id)) c_last = int(last_id, c_int)
        c_type = int(event_type, c_int)

        dummy = wxEvtHandler_Connect(window%ptr, c_first, c_last, c_type, &
            wxClosure_Create(fptr, data_ptr))
    end subroutine

    subroutine wx_disconnect(window, event_type, id, last_id)
        class(wxWindow_t), intent(in) :: window
        integer, intent(in) :: event_type
        integer, intent(in), optional :: id, last_id

        integer(c_int) :: c_first, c_last, c_type, dummy

        c_first = -1_c_int
        if (present(id)) c_first = int(id, c_int)
        c_last = c_first
        if (present(last_id)) c_last = int(last_id, c_int)
        c_type = int(event_type, c_int)

        dummy = wxEvtHandler_Disconnect(window%ptr, c_first, c_last, &
            c_type, -1_c_int)
    end subroutine

    !--- Base event accessors ---

    function wx_event_get_id(evt) result(id)
        type(c_ptr), intent(in) :: evt
        integer :: id
        id = 0
        if (.not. c_associated(evt)) return
        id = int(wxEvent_GetId(evt))
    end function

    function wx_event_get_type(evt) result(etype)
        type(c_ptr), intent(in) :: evt
        integer :: etype
        etype = 0
        if (.not. c_associated(evt)) return
        etype = int(wxEvent_GetEventType(evt))
    end function

    subroutine wx_event_skip(evt, skip)
        type(c_ptr), intent(in) :: evt
        logical, intent(in), optional :: skip
        integer(c_int) :: c_skip
        if (.not. c_associated(evt)) return
        c_skip = 1_c_int
        if (present(skip)) then
            c_skip = 0_c_int
            if (skip) c_skip = 1_c_int
        end if
        call wxEvent_Skip(evt, c_skip)
    end subroutine

    function wx_event_get_timestamp(evt) result(ts)
        type(c_ptr), intent(in) :: evt
        integer :: ts
        ts = 0
        if (.not. c_associated(evt)) return
        ts = int(wxEvent_GetTimestamp(evt))
    end function

    function wx_event_get_skipped(evt) result(skipped)
        type(c_ptr), intent(in) :: evt
        logical :: skipped
        skipped = .false.
        if (.not. c_associated(evt)) return
        skipped = (wxEvent_GetSkipped(evt) /= 0)
    end function

    function wx_event_is_command_event(evt) result(is_cmd)
        type(c_ptr), intent(in) :: evt
        logical :: is_cmd
        is_cmd = .false.
        if (.not. c_associated(evt)) return
        is_cmd = (wxEvent_IsCommandEvent(evt) /= 0)
    end function

    !--- Command event accessors ---

    function wx_command_event_get_string(evt) result(str)
        type(c_ptr), intent(in) :: evt
        character(len=:), allocatable :: str
        type(c_ptr) :: ws_ptr
        if (.not. c_associated(evt)) then
            str = ""
            return
        end if
        ws_ptr = wxCommandEvent_GetString(evt)
        str = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    function wx_command_event_get_selection(evt) result(sel)
        type(c_ptr), intent(in) :: evt
        integer :: sel
        sel = -1
        if (.not. c_associated(evt)) return
        sel = int(wxCommandEvent_GetSelection(evt))
    end function

    function wx_command_event_get_int(evt) result(val)
        type(c_ptr), intent(in) :: evt
        integer :: val
        val = 0
        if (.not. c_associated(evt)) return
        val = int(wxCommandEvent_GetInt(evt))
    end function

    function wx_command_event_get_extra_long(evt) result(val)
        type(c_ptr), intent(in) :: evt
        integer :: val
        val = 0
        if (.not. c_associated(evt)) return
        val = int(wxCommandEvent_GetExtraLong(evt))
    end function

    function wx_command_event_is_checked(evt) result(checked)
        type(c_ptr), intent(in) :: evt
        logical :: checked
        checked = .false.
        if (.not. c_associated(evt)) return
        checked = (wxCommandEvent_IsChecked(evt) /= 0)
    end function

    function wx_command_event_is_selection(evt) result(is_sel)
        type(c_ptr), intent(in) :: evt
        logical :: is_sel
        is_sel = .false.
        if (.not. c_associated(evt)) return
        is_sel = (wxCommandEvent_IsSelection(evt) /= 0)
    end function

end module wx_events
