! Code generated by kwxgen. DO NOT EDIT.
module wx_frame
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    use wx_string, only: to_wxstring, from_wxstring
    implicit none
    private

    ! Creation
    public :: wx_frame_create

    ! Show/hide/close
    public :: wx_frame_show, wx_frame_hide, wx_frame_close

    ! Status bar
    public :: wx_frame_create_status_bar, wx_frame_set_status_text
    public :: wx_frame_push_status_text, wx_frame_pop_status_text

    ! Menu bar
    public :: wx_frame_set_menu_bar, wx_frame_get_menu_bar

    ! Toolbar
    public :: wx_frame_create_tool_bar, wx_frame_get_tool_bar

    ! Window ops
    public :: wx_frame_center, wx_frame_set_size

    ! TopLevelWindow ops
    public :: wx_frame_restore, wx_frame_maximize, wx_frame_iconize
    public :: wx_frame_is_maximized, wx_frame_is_iconized
    public :: wx_frame_show_full_screen, wx_frame_is_full_screen
    public :: wx_frame_get_title, wx_frame_set_title
    public :: wx_frame_is_active
    public :: wx_frame_enable_close_button
    public :: wx_frame_enable_maximize_button
    public :: wx_frame_enable_minimize_button
    public :: wx_frame_request_user_attention

contains

    !--- Creation ---

    function wx_frame_create(title, parent, id, x, y, width, height, style) &
            result(frame)
        character(len=*), intent(in) :: title
        class(wxWindow_t), intent(in), optional :: parent
        integer, intent(in), optional :: id
        integer, intent(in), optional :: x, y, width, height
        integer(c_long), intent(in), optional :: style
        type(wxFrame_t) :: frame

        type(c_ptr) :: parent_ptr, title_ptr
        integer(c_int) :: c_id, c_x, c_y, c_w, c_h
        integer(c_long) :: c_style

        parent_ptr = c_null_ptr
        if (present(parent)) parent_ptr = parent%ptr
        c_id = wxID_ANY()
        if (present(id)) c_id = int(id, c_int)
        c_x = -1_c_int
        if (present(x)) c_x = int(x, c_int)
        c_y = -1_c_int
        if (present(y)) c_y = int(y, c_int)
        c_w = -1_c_int
        if (present(width)) c_w = int(width, c_int)
        c_h = -1_c_int
        if (present(height)) c_h = int(height, c_int)
        c_style = wxDEFAULT_FRAME_STYLE()
        if (present(style)) c_style = style

        title_ptr = to_wxstring(title)
        frame%ptr = wxFrame_Create(parent_ptr, c_id, title_ptr, &
            c_x, c_y, c_w, c_h, c_style)
        call wxString_Delete(title_ptr)
    end function

    !--- Show/hide/close ---

    subroutine wx_frame_show(frame)
        type(wxFrame_t), intent(in) :: frame
        integer(c_int) :: dummy
        dummy = wxWindow_Show(frame%ptr)
    end subroutine

    subroutine wx_frame_hide(frame)
        type(wxFrame_t), intent(in) :: frame
        integer(c_int) :: dummy
        dummy = wxWindow_Hide(frame%ptr)
    end subroutine

    subroutine wx_frame_close(frame, force)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: force
        integer(c_int) :: c_force, dummy
        c_force = 0_c_int
        if (present(force)) then
            if (force) c_force = 1_c_int
        end if
        dummy = wxWindow_Close(frame%ptr, c_force)
    end subroutine

    !--- Status bar ---

    subroutine wx_frame_create_status_bar(frame, number, style)
        type(wxFrame_t), intent(in) :: frame
        integer, intent(in), optional :: number
        integer(c_long), intent(in), optional :: style
        type(c_ptr) :: result_
        integer(c_int) :: c_num
        integer(c_long) :: c_style
        c_num = 1_c_int
        if (present(number)) c_num = int(number, c_int)
        c_style = 0_c_long
        if (present(style)) c_style = style
        result_ = wxFrame_CreateStatusBar(frame%ptr, c_num, c_style)
    end subroutine

    subroutine wx_frame_set_status_text(frame, text, number)
        type(wxFrame_t), intent(in) :: frame
        character(len=*), intent(in) :: text
        integer, intent(in), optional :: number
        type(c_ptr) :: text_ptr
        integer(c_int) :: c_num
        c_num = 0_c_int
        if (present(number)) c_num = int(number, c_int)
        text_ptr = to_wxstring(text)
        call wxFrame_SetStatusText(frame%ptr, text_ptr, c_num)
        call wxString_Delete(text_ptr)
    end subroutine

    subroutine wx_frame_push_status_text(frame, text, number)
        type(wxFrame_t), intent(in) :: frame
        character(len=*), intent(in) :: text
        integer, intent(in), optional :: number
        type(c_ptr) :: text_ptr
        integer(c_int) :: c_num
        c_num = 0_c_int
        if (present(number)) c_num = int(number, c_int)
        text_ptr = to_wxstring(text)
        call wxFrame_PushStatusText(frame%ptr, text_ptr, c_num)
        call wxString_Delete(text_ptr)
    end subroutine

    subroutine wx_frame_pop_status_text(frame, number)
        type(wxFrame_t), intent(in) :: frame
        integer, intent(in), optional :: number
        integer(c_int) :: c_num
        c_num = 0_c_int
        if (present(number)) c_num = int(number, c_int)
        call wxFrame_PopStatusText(frame%ptr, c_num)
    end subroutine

    !--- Menu bar ---

    subroutine wx_frame_set_menu_bar(frame, menubar)
        type(wxFrame_t), intent(in) :: frame
        type(wxMenuBar_t), intent(in) :: menubar
        call wxFrame_SetMenuBar(frame%ptr, menubar%ptr)
    end subroutine

    function wx_frame_get_menu_bar(frame) result(menubar)
        type(wxFrame_t), intent(in) :: frame
        type(wxMenuBar_t) :: menubar
        menubar%ptr = wxFrame_GetMenuBar(frame%ptr)
    end function

    !--- Toolbar ---

    function wx_frame_create_tool_bar(frame, style) result(toolbar)
        type(wxFrame_t), intent(in) :: frame
        integer(c_long), intent(in), optional :: style
        type(wxToolBar_t) :: toolbar
        integer(c_long) :: c_style
        c_style = -1_c_long
        if (present(style)) c_style = style
        toolbar%ptr = wxFrame_CreateToolBar(frame%ptr, c_style)
    end function

    function wx_frame_get_tool_bar(frame) result(toolbar)
        type(wxFrame_t), intent(in) :: frame
        type(wxToolBar_t) :: toolbar
        toolbar%ptr = wxFrame_GetToolBar(frame%ptr)
    end function

    !--- Window ops ---

    subroutine wx_frame_center(frame, direction)
        type(wxFrame_t), intent(in) :: frame
        integer, intent(in), optional :: direction
        integer(c_int) :: dir
        dir = wxBOTH()
        if (present(direction)) dir = int(direction, c_int)
        call wxWindow_CenterOnParent(frame%ptr, dir)
    end subroutine

    subroutine wx_frame_set_size(frame, width, height)
        type(wxFrame_t), intent(in) :: frame
        integer, intent(in) :: width, height
        call wxWindow_SetSize(frame%ptr, -1_c_int, -1_c_int, &
            int(width, c_int), int(height, c_int), 0_c_int)
    end subroutine

    !--- TopLevelWindow ops ---

    subroutine wx_frame_restore(frame)
        type(wxFrame_t), intent(in) :: frame
        call wxTopLevelWindow_Restore(frame%ptr)
    end subroutine

    subroutine wx_frame_maximize(frame, maximize)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: maximize
        integer(c_int) :: c_max
        c_max = 1_c_int
        if (present(maximize)) then
            c_max = 0_c_int
            if (maximize) c_max = 1_c_int
        end if
        call wxTopLevelWindow_Maximize(frame%ptr, c_max)
    end subroutine

    subroutine wx_frame_iconize(frame, iconize)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: iconize
        integer(c_int) :: c_ico, dummy
        c_ico = 1_c_int
        if (present(iconize)) then
            c_ico = 0_c_int
            if (iconize) c_ico = 1_c_int
        end if
        dummy = wxTopLevelWindow_Iconize(frame%ptr, c_ico)
    end subroutine

    function wx_frame_is_maximized(frame) result(maximized)
        type(wxFrame_t), intent(in) :: frame
        logical :: maximized
        maximized = (wxTopLevelWindow_IsMaximized(frame%ptr) /= 0)
    end function

    function wx_frame_is_iconized(frame) result(iconized)
        type(wxFrame_t), intent(in) :: frame
        logical :: iconized
        iconized = (wxTopLevelWindow_IsIconized(frame%ptr) /= 0)
    end function

    function wx_frame_show_full_screen(frame, show, style) result(ok)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in) :: show
        integer(c_long), intent(in), optional :: style
        logical :: ok
        integer(c_int) :: c_show
        integer(c_long) :: c_style
        c_show = 0_c_int
        if (show) c_show = 1_c_int
        c_style = 0_c_long
        if (present(style)) c_style = style
        ok = (wxTopLevelWindow_ShowFullScreen(frame%ptr, c_show, c_style) /= 0)
    end function

    function wx_frame_is_full_screen(frame) result(full)
        type(wxFrame_t), intent(in) :: frame
        logical :: full
        full = (wxTopLevelWindow_IsFullScreen(frame%ptr) /= 0)
    end function

    function wx_frame_get_title(frame) result(title)
        type(wxFrame_t), intent(in) :: frame
        character(len=:), allocatable :: title
        type(c_ptr) :: ws_ptr
        ws_ptr = wxTopLevelWindow_GetTitle(frame%ptr)
        title = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_frame_set_title(frame, title)
        type(wxFrame_t), intent(in) :: frame
        character(len=*), intent(in) :: title
        type(c_ptr) :: title_ptr
        title_ptr = to_wxstring(title)
        call wxTopLevelWindow_SetTitle(frame%ptr, title_ptr)
        call wxString_Delete(title_ptr)
    end subroutine

    function wx_frame_is_active(frame) result(active)
        type(wxFrame_t), intent(in) :: frame
        logical :: active
        active = (wxTopLevelWindow_IsActive(frame%ptr) /= 0)
    end function

    function wx_frame_enable_close_button(frame, enable) result(ok)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: enable
        logical :: ok
        integer(c_int) :: c_en
        c_en = 1_c_int
        if (present(enable)) then
            c_en = 0_c_int
            if (enable) c_en = 1_c_int
        end if
        ok = (wxTopLevelWindow_EnableCloseButton(frame%ptr, c_en) /= 0)
    end function

    function wx_frame_enable_maximize_button(frame, enable) result(ok)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: enable
        logical :: ok
        integer(c_int) :: c_en
        c_en = 1_c_int
        if (present(enable)) then
            c_en = 0_c_int
            if (enable) c_en = 1_c_int
        end if
        ok = (wxTopLevelWindow_EnableMaximizeButton(frame%ptr, c_en) /= 0)
    end function

    function wx_frame_enable_minimize_button(frame, enable) result(ok)
        type(wxFrame_t), intent(in) :: frame
        logical, intent(in), optional :: enable
        logical :: ok
        integer(c_int) :: c_en
        c_en = 1_c_int
        if (present(enable)) then
            c_en = 0_c_int
            if (enable) c_en = 1_c_int
        end if
        ok = (wxTopLevelWindow_EnableMinimizeButton(frame%ptr, c_en) /= 0)
    end function

    subroutine wx_frame_request_user_attention(frame, flags)
        type(wxFrame_t), intent(in) :: frame
        integer, intent(in), optional :: flags
        integer(c_int) :: c_flags
        c_flags = 0_c_int
        if (present(flags)) c_flags = int(flags, c_int)
        call wxTopLevelWindow_RequestUserAttention(frame%ptr, c_flags)
    end subroutine

end module wx_frame
