! Code generated by kwxgen. DO NOT EDIT.
module wx_menus
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    use wx_string, only: to_wxstring, from_wxstring
    implicit none
    private

    ! wxMenu
    public :: wx_menu_create, wx_menu_delete
    public :: wx_menu_append, wx_menu_append_separator
    public :: wx_menu_append_check_item
    public :: wx_menu_enable, wx_menu_check
    public :: wx_menu_is_enabled, wx_menu_is_checked
    public :: wx_menu_get_item_count

    ! wxMenuBar
    public :: wx_menubar_create, wx_menubar_append
    public :: wx_menubar_get_menu_count, wx_menubar_get_menu
    public :: wx_menubar_enable_top

    ! wxMenuItem
    public :: wx_menuitem_create, wx_menuitem_delete
    public :: wx_menuitem_get_id, wx_menuitem_is_separator
    public :: wx_menuitem_get_label, wx_menuitem_set_label
    public :: wx_menuitem_is_checked, wx_menuitem_check
    public :: wx_menuitem_is_enabled, wx_menuitem_enable

contains

    !--- wxMenu ---

    function wx_menu_create(title) result(menu)
        character(len=*), intent(in), optional :: title
        type(wxMenu_t) :: menu
        type(c_ptr) :: title_ptr

        if (present(title)) then
            title_ptr = to_wxstring(title)
        else
            title_ptr = to_wxstring("")
        end if
        menu%ptr = wxMenu_Create(title_ptr, 0_c_long)
        call wxString_Delete(title_ptr)
    end function

    subroutine wx_menu_delete(menu)
        type(wxMenu_t), intent(inout) :: menu
        call wxMenu_DeletePointer(menu%ptr)
        menu%ptr = c_null_ptr
    end subroutine

    subroutine wx_menu_append(menu, id, text, help)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        character(len=*), intent(in) :: text
        character(len=*), intent(in), optional :: help
        type(c_ptr) :: text_ptr, help_ptr

        text_ptr = to_wxstring(text)
        if (present(help)) then
            help_ptr = to_wxstring(help)
        else
            help_ptr = to_wxstring("")
        end if
        call wxMenu_Append(menu%ptr, int(id, c_int), text_ptr, &
            help_ptr, 0_c_int)
        call wxString_Delete(text_ptr)
        call wxString_Delete(help_ptr)
    end subroutine

    subroutine wx_menu_append_separator(menu)
        type(wxMenu_t), intent(in) :: menu
        call wxMenu_AppendSeparator(menu%ptr)
    end subroutine

    subroutine wx_menu_append_check_item(menu, id, text, help)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        character(len=*), intent(in) :: text
        character(len=*), intent(in), optional :: help
        type(c_ptr) :: text_ptr, help_ptr

        text_ptr = to_wxstring(text)
        if (present(help)) then
            help_ptr = to_wxstring(help)
        else
            help_ptr = to_wxstring("")
        end if
        call wxMenu_AppendCheckItem(menu%ptr, int(id, c_int), &
            text_ptr, help_ptr)
        call wxString_Delete(text_ptr)
        call wxString_Delete(help_ptr)
    end subroutine

    subroutine wx_menu_enable(menu, id, enable)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        logical, intent(in) :: enable
        integer(c_int) :: c_en
        c_en = 0_c_int
        if (enable) c_en = 1_c_int
        call wxMenu_Enable(menu%ptr, int(id, c_int), c_en)
    end subroutine

    subroutine wx_menu_check(menu, id, check_)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        logical, intent(in) :: check_
        integer(c_int) :: c_chk
        c_chk = 0_c_int
        if (check_) c_chk = 1_c_int
        call wxMenu_Check(menu%ptr, int(id, c_int), c_chk)
    end subroutine

    function wx_menu_is_enabled(menu, id) result(enabled)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        logical :: enabled
        enabled = (wxMenu_IsEnabled(menu%ptr, int(id, c_int)) /= 0)
    end function

    function wx_menu_is_checked(menu, id) result(checked)
        type(wxMenu_t), intent(in) :: menu
        integer, intent(in) :: id
        logical :: checked
        checked = (wxMenu_IsChecked(menu%ptr, int(id, c_int)) /= 0)
    end function

    function wx_menu_get_item_count(menu) result(n)
        type(wxMenu_t), intent(in) :: menu
        integer :: n
        n = int(wxMenu_GetMenuItemCount(menu%ptr))
    end function

    !--- wxMenuBar ---

    function wx_menubar_create() result(menubar)
        type(wxMenuBar_t) :: menubar
        menubar%ptr = wxMenuBar_Create(0_c_int)
    end function

    subroutine wx_menubar_append(menubar, menu, title)
        type(wxMenuBar_t), intent(in) :: menubar
        type(wxMenu_t), intent(in) :: menu
        character(len=*), intent(in) :: title
        integer(c_int) :: dummy
        type(c_ptr) :: title_ptr
        title_ptr = to_wxstring(title)
        dummy = wxMenuBar_Append(menubar%ptr, menu%ptr, title_ptr)
        call wxString_Delete(title_ptr)
    end subroutine

    function wx_menubar_get_menu_count(menubar) result(n)
        type(wxMenuBar_t), intent(in) :: menubar
        integer :: n
        n = int(wxMenuBar_GetMenuCount(menubar%ptr))
    end function

    function wx_menubar_get_menu(menubar, pos) result(menu)
        type(wxMenuBar_t), intent(in) :: menubar
        integer, intent(in) :: pos
        type(wxMenu_t) :: menu
        menu%ptr = wxMenuBar_GetMenu(menubar%ptr, int(pos, c_int))
    end function

    subroutine wx_menubar_enable_top(menubar, pos, enable)
        type(wxMenuBar_t), intent(in) :: menubar
        integer, intent(in) :: pos
        logical, intent(in) :: enable
        integer(c_int) :: c_en
        c_en = 0_c_int
        if (enable) c_en = 1_c_int
        call wxMenuBar_EnableTop(menubar%ptr, int(pos, c_int), c_en)
    end subroutine

    !--- wxMenuItem ---

    function wx_menuitem_create(id, text, help) &
            result(item)
        integer, intent(in), optional :: id
        character(len=*), intent(in), optional :: text, help
        type(wxMenuItem_t) :: item

        ! Create a default menu item then configure
        item%ptr = wxMenuItem_Create()

        if (present(id)) then
            call wxMenuItem_SetId(item%ptr, int(id, c_int))
        end if

        if (present(text)) then
            block
                type(c_ptr) :: text_ptr
                text_ptr = to_wxstring(text)
                call wxMenuItem_SetItemLabel(item%ptr, text_ptr)
                call wxString_Delete(text_ptr)
            end block
        end if

        if (present(help)) then
            block
                type(c_ptr) :: help_ptr
                help_ptr = to_wxstring(help)
                call wxMenuItem_SetHelp(item%ptr, help_ptr)
                call wxString_Delete(help_ptr)
            end block
        end if
    end function

    subroutine wx_menuitem_delete(item)
        type(wxMenuItem_t), intent(inout) :: item
        call wxMenuItem_Delete(item%ptr)
        item%ptr = c_null_ptr
    end subroutine

    function wx_menuitem_get_id(item) result(id)
        type(wxMenuItem_t), intent(in) :: item
        integer :: id
        id = int(wxMenuItem_GetId(item%ptr))
    end function

    function wx_menuitem_is_separator(item) result(is_sep)
        type(wxMenuItem_t), intent(in) :: item
        logical :: is_sep
        is_sep = (wxMenuItem_IsSeparator(item%ptr) /= 0)
    end function

    function wx_menuitem_get_label(item) result(label)
        type(wxMenuItem_t), intent(in) :: item
        character(len=:), allocatable :: label
        type(c_ptr) :: ws_ptr
        ws_ptr = wxMenuItem_GetItemLabelText(item%ptr)
        label = from_wxstring(ws_ptr)
        call wxString_Delete(ws_ptr)
    end function

    subroutine wx_menuitem_set_label(item, label)
        type(wxMenuItem_t), intent(in) :: item
        character(len=*), intent(in) :: label
        type(c_ptr) :: label_ptr
        label_ptr = to_wxstring(label)
        call wxMenuItem_SetItemLabel(item%ptr, label_ptr)
        call wxString_Delete(label_ptr)
    end subroutine

    function wx_menuitem_is_checked(item) result(checked)
        type(wxMenuItem_t), intent(in) :: item
        logical :: checked
        checked = (wxMenuItem_IsChecked(item%ptr) /= 0)
    end function

    subroutine wx_menuitem_check(item, check_)
        type(wxMenuItem_t), intent(in) :: item
        logical, intent(in) :: check_
        integer(c_int) :: c_chk
        c_chk = 0_c_int
        if (check_) c_chk = 1_c_int
        call wxMenuItem_Check(item%ptr, c_chk)
    end subroutine

    function wx_menuitem_is_enabled(item) result(enabled)
        type(wxMenuItem_t), intent(in) :: item
        logical :: enabled
        enabled = (wxMenuItem_IsEnabled(item%ptr) /= 0)
    end function

    subroutine wx_menuitem_enable(item, enable)
        type(wxMenuItem_t), intent(in) :: item
        logical, intent(in) :: enable
        integer(c_int) :: c_en
        c_en = 0_c_int
        if (enable) c_en = 1_c_int
        call wxMenuItem_Enable(item%ptr, c_en)
    end subroutine

end module wx_menus
