! Code generated by kwxgen. DO NOT EDIT.
module wx_string
    use, intrinsic :: iso_c_binding
    use kwx_types
    implicit none
    private

    public :: to_wxstring, from_wxstring, wxString_Delete

    interface
        function wxString_CreateUTF8(str) bind(C, name="wxString_CreateUTF8")
            import :: c_ptr, c_char
            character(kind=c_char), dimension(*), intent(in) :: str
            type(c_ptr) :: wxString_CreateUTF8
        end function

        function wxString_GetString(wx_str, buffer) bind(C, name="wxString_GetString")
            import :: c_ptr, c_int
            type(c_ptr), value :: wx_str
            type(c_ptr), value :: buffer
            integer(c_int) :: wxString_GetString
        end function

        subroutine wxString_Delete_C(wx_str) bind(C, name="wxString_Delete")
            import :: c_ptr
            type(c_ptr), value :: wx_str
        end subroutine

        function wxString_Length(wx_str) bind(C, name="wxString_Length")
            import :: c_ptr, c_int
            type(c_ptr), value :: wx_str
            integer(c_int) :: wxString_Length
        end function
    end interface

contains

    function to_wxstring(fstring) result(ptr)
        character(len=*), intent(in) :: fstring
        type(c_ptr) :: ptr
        character(kind=c_char, len=:), allocatable :: cstr

        cstr = trim(fstring) // c_null_char
        ptr = wxString_CreateUTF8(cstr)
    end function to_wxstring

    function from_wxstring(wx_str_ptr) result(fstring)
        type(c_ptr), intent(in) :: wx_str_ptr
        character(len=:), allocatable :: fstring
        integer(c_int) :: slen, i
        character(kind=c_char), dimension(:), allocatable, target :: buffer
        type(c_ptr) :: buf_ptr

        if (.not. c_associated(wx_str_ptr)) then
            fstring = ""
            return
        end if

        slen = wxString_GetString(wx_str_ptr, c_null_ptr)
        if (slen <= 0) then
            fstring = ""
            return
        end if

        allocate(buffer(slen + 1))
        buf_ptr = c_loc(buffer(1))
        slen = wxString_GetString(wx_str_ptr, buf_ptr)

        allocate(character(len=slen) :: fstring)
        do i = 1, slen
            fstring(i:i) = buffer(i)
        end do
    end function from_wxstring

    subroutine wxString_Delete(wx_str_ptr)
        type(c_ptr), intent(inout) :: wx_str_ptr
        if (c_associated(wx_str_ptr)) then
            call wxString_Delete_C(wx_str_ptr)
            wx_str_ptr = c_null_ptr
        end if
    end subroutine wxString_Delete

end module wx_string
