! Code generated by kwxgen. DO NOT EDIT.
module wx_sizers
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    implicit none
    private

    ! wxBoxSizer
    public :: wx_box_sizer_create, wx_box_sizer_get_orientation

    ! wxSizer operations
    public :: wx_sizer_add_window, wx_sizer_add_sizer
    public :: wx_sizer_add_spacer, wx_sizer_add_stretch_spacer
    public :: wx_sizer_layout, wx_sizer_fit, wx_sizer_set_size_hints

    ! Convenience
    public :: wx_window_set_sizer

contains

    !--- wxBoxSizer ---

    function wx_box_sizer_create(orient) result(sizer)
        integer, intent(in) :: orient
        type(wxBoxSizer_t) :: sizer
        sizer%ptr = wxBoxSizer_Create(int(orient, c_int))
    end function

    function wx_box_sizer_get_orientation(sizer) result(orient)
        type(wxBoxSizer_t), intent(in) :: sizer
        integer :: orient
        orient = int(wxBoxSizer_GetOrientation(sizer%ptr))
    end function

    !--- wxSizer operations ---

    subroutine wx_sizer_add_window(sizer, window, proportion, flag, border)
        class(wxSizer_t), intent(in) :: sizer
        class(wxWindow_t), intent(in) :: window
        integer, intent(in), optional :: proportion, flag, border
        integer(c_int) :: c_prop, c_flag, c_border
        c_prop = 0_c_int
        if (present(proportion)) c_prop = int(proportion, c_int)
        c_flag = 0_c_int
        if (present(flag)) c_flag = int(flag, c_int)
        c_border = 0_c_int
        if (present(border)) c_border = int(border, c_int)
        call wxSizer_AddWindow(sizer%ptr, window%ptr, &
            c_prop, c_flag, c_border, c_null_ptr)
    end subroutine

    subroutine wx_sizer_add_sizer(sizer, child, proportion, flag, border)
        class(wxSizer_t), intent(in) :: sizer
        class(wxSizer_t), intent(in) :: child
        integer, intent(in), optional :: proportion, flag, border
        integer(c_int) :: c_prop, c_flag, c_border
        c_prop = 0_c_int
        if (present(proportion)) c_prop = int(proportion, c_int)
        c_flag = 0_c_int
        if (present(flag)) c_flag = int(flag, c_int)
        c_border = 0_c_int
        if (present(border)) c_border = int(border, c_int)
        call wxSizer_AddSizer(sizer%ptr, child%ptr, &
            c_prop, c_flag, c_border, c_null_ptr)
    end subroutine

    subroutine wx_sizer_add_spacer(sizer, width, height, proportion, flag, &
            border)
        class(wxSizer_t), intent(in) :: sizer
        integer, intent(in) :: width, height
        integer, intent(in), optional :: proportion, flag, border
        integer(c_int) :: c_prop, c_flag, c_border
        c_prop = 0_c_int
        if (present(proportion)) c_prop = int(proportion, c_int)
        c_flag = 0_c_int
        if (present(flag)) c_flag = int(flag, c_int)
        c_border = 0_c_int
        if (present(border)) c_border = int(border, c_int)
        call wxSizer_Add(sizer%ptr, int(width, c_int), &
            int(height, c_int), c_prop, c_flag, c_border, c_null_ptr)
    end subroutine

    subroutine wx_sizer_add_stretch_spacer(sizer, proportion)
        class(wxSizer_t), intent(in) :: sizer
        integer, intent(in), optional :: proportion
        integer(c_int) :: c_prop
        c_prop = 1_c_int
        if (present(proportion)) c_prop = int(proportion, c_int)
        call wxSizer_AddStretchSpacer(sizer%ptr, c_prop)
    end subroutine

    subroutine wx_sizer_layout(sizer)
        class(wxSizer_t), intent(in) :: sizer
        call wxSizer_Layout(sizer%ptr)
    end subroutine

    subroutine wx_sizer_fit(sizer, window)
        class(wxSizer_t), intent(in) :: sizer
        class(wxWindow_t), intent(in) :: window
        call wxSizer_Fit(sizer%ptr, window%ptr)
    end subroutine

    subroutine wx_sizer_set_size_hints(sizer, window)
        class(wxSizer_t), intent(in) :: sizer
        class(wxWindow_t), intent(in) :: window
        call wxSizer_SetSizeHints(sizer%ptr, window%ptr)
    end subroutine

    !--- Convenience ---

    subroutine wx_window_set_sizer(window, sizer)
        class(wxWindow_t), intent(in) :: window
        class(wxSizer_t), intent(in) :: sizer
        call wxWindow_SetSizer(window%ptr, sizer%ptr, 1_c_int)
    end subroutine

end module wx_sizers
