! Code generated by kwxgen. DO NOT EDIT.
module wx_window
    use, intrinsic :: iso_c_binding
    use kwx_types
    use kwxffi
    implicit none
    private

    ! Visibility and state
    public :: wx_window_show, wx_window_hide
    public :: wx_window_enable, wx_window_disable
    public :: wx_window_is_enabled, wx_window_is_shown

    ! Size and position
    public :: wx_window_set_size, wx_window_move
    public :: wx_window_get_id

    ! Focus
    public :: wx_window_set_focus, wx_window_has_focus

    ! Refresh and update
    public :: wx_window_refresh, wx_window_update

    ! Layout
    public :: wx_window_center, wx_window_fit, wx_window_layout

    ! Destruction
    public :: wx_window_destroy, wx_window_close

    ! Hierarchy
    public :: wx_window_get_parent, wx_window_is_top_level

    ! Freeze/thaw
    public :: wx_window_freeze, wx_window_thaw

    ! Z-order
    public :: wx_window_raise, wx_window_lower

contains

    !--- Visibility and state ---

    function wx_window_show(window) result(shown)
        class(wxWindow_t), intent(in) :: window
        logical :: shown
        shown = (wxWindow_Show(window%ptr) /= 0)
    end function

    function wx_window_hide(window) result(hidden)
        class(wxWindow_t), intent(in) :: window
        logical :: hidden
        hidden = (wxWindow_Hide(window%ptr) /= 0)
    end function

    subroutine wx_window_enable(window)
        class(wxWindow_t), intent(in) :: window
        integer(c_int) :: result_
        result_ = wxWindow_Enable(window%ptr)
    end subroutine

    subroutine wx_window_disable(window)
        class(wxWindow_t), intent(in) :: window
        integer(c_int) :: result_
        result_ = wxWindow_Disable(window%ptr)
    end subroutine

    function wx_window_is_enabled(window) result(enabled)
        class(wxWindow_t), intent(in) :: window
        logical :: enabled
        enabled = (wxWindow_IsEnabled(window%ptr) /= 0)
    end function

    function wx_window_is_shown(window) result(shown)
        class(wxWindow_t), intent(in) :: window
        logical :: shown
        shown = (wxWindow_IsShown(window%ptr) /= 0)
    end function

    !--- Size and position ---

    subroutine wx_window_set_size(window, x, y, width, height)
        class(wxWindow_t), intent(in) :: window
        integer, intent(in) :: x, y, width, height
        call wxWindow_SetSize(window%ptr, int(x, c_int), int(y, c_int), &
            int(width, c_int), int(height, c_int), 0_c_int)
    end subroutine

    subroutine wx_window_move(window, x, y)
        class(wxWindow_t), intent(in) :: window
        integer, intent(in) :: x, y
        call wxWindow_Move(window%ptr, int(x, c_int), int(y, c_int), 0_c_int)
    end subroutine

    function wx_window_get_id(window) result(id)
        class(wxWindow_t), intent(in) :: window
        integer :: id
        id = int(wxWindow_GetId(window%ptr))
    end function

    !--- Focus ---

    subroutine wx_window_set_focus(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_SetFocus(window%ptr)
    end subroutine

    function wx_window_has_focus(window) result(focused)
        class(wxWindow_t), intent(in) :: window
        logical :: focused
        focused = (wxWindow_HasFocus(window%ptr) /= 0)
    end function

    !--- Refresh and update ---

    subroutine wx_window_refresh(window, erase_background)
        class(wxWindow_t), intent(in) :: window
        logical, intent(in), optional :: erase_background
        integer(c_int) :: erase
        erase = 1_c_int
        if (present(erase_background)) then
            erase = 0_c_int
            if (erase_background) erase = 1_c_int
        end if
        call wxWindow_Refresh(window%ptr, erase)
    end subroutine

    subroutine wx_window_update(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_UpdateWindowUI(window%ptr, 0_c_int)
    end subroutine

    !--- Layout ---

    subroutine wx_window_center(window, direction)
        class(wxWindow_t), intent(in) :: window
        integer, intent(in), optional :: direction
        integer(c_int) :: dir
        dir = wxBOTH()
        if (present(direction)) dir = int(direction, c_int)
        call wxWindow_CenterOnParent(window%ptr, dir)
    end subroutine

    subroutine wx_window_fit(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_Fit(window%ptr)
    end subroutine

    function wx_window_layout(window) result(ok)
        class(wxWindow_t), intent(in) :: window
        logical :: ok
        ok = (wxWindow_Layout(window%ptr) /= 0)
    end function

    !--- Destruction ---

    function wx_window_destroy(window) result(destroyed)
        class(wxWindow_t), intent(inout) :: window
        logical :: destroyed
        destroyed = (wxWindow_Destroy(window%ptr) /= 0)
        window%ptr = c_null_ptr
    end function

    function wx_window_close(window, force) result(closed)
        class(wxWindow_t), intent(in) :: window
        logical, intent(in), optional :: force
        logical :: closed
        integer(c_int) :: c_force
        c_force = 0_c_int
        if (present(force)) then
            if (force) c_force = 1_c_int
        end if
        closed = (wxWindow_Close(window%ptr, c_force) /= 0)
    end function

    !--- Hierarchy ---

    function wx_window_get_parent(window) result(parent)
        class(wxWindow_t), intent(in) :: window
        type(wxWindow_t) :: parent
        parent%ptr = wxWindow_GetParent(window%ptr)
    end function

    function wx_window_is_top_level(window) result(is_top)
        class(wxWindow_t), intent(in) :: window
        logical :: is_top
        is_top = (wxWindow_IsTopLevel(window%ptr) /= 0)
    end function

    !--- Freeze/thaw ---

    subroutine wx_window_freeze(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_Freeze(window%ptr)
    end subroutine

    subroutine wx_window_thaw(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_Thaw(window%ptr)
    end subroutine

    !--- Z-order ---

    subroutine wx_window_raise(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_Raise(window%ptr)
    end subroutine

    subroutine wx_window_lower(window)
        class(wxWindow_t), intent(in) :: window
        call wxWindow_Lower(window%ptr)
    end subroutine

end module wx_window
